
// Este código gera uma tabela de calendário a partir de uma base de dados de vendas.

let
    DataMin = List.Min(BaseVendas[Data da Venda]),
    DataMax = List.Max(BaseVendas[Data da Venda]),
    QtdeDias = Duration.Days(DataMax - DataMin),
    Personalizar1 = List.Dates(DataMin, QtdeDias, #duration(1,0,0,0)),
    #"Convertido para Tabela" = Table.FromList(Personalizar1, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    #"Colunas Renomeadas" = Table.RenameColumns(#"Convertido para Tabela", {{"Column1", "Datas"}}),
    #"Tipo Alterado" = Table.TransformColumnTypes(#"Colunas Renomeadas", {{"Datas", type date}}),
    #"Ano Inserido" = Table.AddColumn(#"Tipo Alterado", "Ano", each Date.Year([Datas]), Int64.Type),
    #"Nome do Mês Inserido" = Table.AddColumn(#"Ano Inserido", "Nome do Mês", each Date.MonthName([Datas]), type text),
    #"Mês Inserido" = Table.AddColumn(#"Nome do Mês Inserido", "Mês", each Date.Month([Datas]), Int64.Type),
    #"Início do Mês Inserido" = Table.AddColumn(#"Mês Inserido", "Início do Mês", each Date.StartOfMonth([Datas]), type date),
    #"Fim do Mês Inserido" = Table.AddColumn(#"Início do Mês Inserido", "Fim do Mês", each Date.EndOfMonth([Datas]), type date),
    #"Nome do Dia Inserido" = Table.AddColumn(#"Fim do Mês Inserido", "Nome do Dia", each Date.DayOfWeekName([Datas]), type text),
    #"Dia Inserido" = Table.AddColumn(#"Nome do Dia Inserido", "Dia", each Date.Day([Datas]), Int64.Type),
    #"Dia da Semana Inserido" = Table.AddColumn(#"Dia Inserido", "Dia da Semana", each Date.DayOfWeek([Datas]), Int64.Type),
    #"Linhas Classificadas" = Table.Sort(#"Dia da Semana Inserido", {{"Datas", Order.Ascending}})
in
    #"Linhas Classificadas"
